version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
    build:
      commands:
        - echo skipping build stage...
    post_build:
      commands:
        - echo Testing the application
        - npm test
    